# Generated by Django 5.0.1 on 2024-01-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('cize', 'size')], max_length=100),
        ),
    ]
